# Generated by Django 2.2.4 on 2019-08-25 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tossapp_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('display_photo', models.ImageField(default=None, upload_to=tossapp_api.models.content_file_name)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('times_played', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=13)),
                ('transaction_type', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw'), (2, 'Transfer')])),
                ('payment_method', models.IntegerField(choices=[(0, 'Mobile Money'), (1, 'Tossapp transfer')])),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('status', models.IntegerField(choices=[(0, 'Complete'), (1, 'Pending'), (2, 'Failed')])),
                ('timestamp', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Success'), (1, 'Information'), (2, 'Warning'), (3, 'Error'), (4, 'Account')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Lose'), (1, 'Win'), (3, 'Pending')])),
                ('win_amount', models.FloatField(blank=True, default=0.0)),
                ('loss_amount', models.FloatField(blank=True, default=0.0)),
                ('service_fee', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tossapp_api.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game statistic',
                'verbose_name_plural': 'Game statistics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
