# Generated by Django 3.0.6 on 2020-05-27 10:26

from django.db import migrations, models
import tossapp_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp_api', '0003_system_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to=tossapp_api.models.content_file_name),
        ),
    ]
