# Generated by Django 3.0.6 on 2020-05-28 15:52

from django.db import migrations, models
import tossapp_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp_api', '0004_auto_20200527_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='display_photo',
            field=models.ImageField(blank=True, default='games/Daily_Lotto.jpg', null=True, upload_to=tossapp_api.models.content_file_name),
        ),
    ]
