# Generated by Django 3.0.6 on 2020-07-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp_api', '0005_auto_20200528_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System_info',
        ),
    ]
