# Generated by Django 2.2.4 on 2019-10-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylotto',
            options={'ordering': ['lotto_id']},
        ),
    ]
