# Generated by Django 2.2.4 on 2019-10-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_api', '0002_auto_20191016_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylotto',
            options={'ordering': ['-lotto_id']},
        ),
    ]
