# Generated by Django 2.2.4 on 2019-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_api', '0003_auto_20191016_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylottoticket',
            name='ticket_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
