# Generated by Django 2.2.4 on 2019-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_api', '0004_dailylottoticket_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylottoticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
    ]
