# Generated by Django 2.2.4 on 2019-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_api', '0006_auto_20191016_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylottoticket',
            name='ticket_no',
            field=models.CharField(blank=True, default='T2019101615286', max_length=100, null=True, unique=True),
        ),
    ]
