# Generated by Django 2.2.4 on 2019-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_api', '0007_auto_20191016_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylottoticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
