# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=15, unique=True)),
                ('phone_number', models.CharField(error_messages={'unique': 'A user with this phone number already exists.'}, max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=30)),
                ('referrer_prize', models.IntegerField(default=0, editable=False)),
                ('timestamp', models.DateTimeField(editable=False)),
                ('profile_photo', models.ImageField(null=True, upload_to='users')),
                ('points', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, default='', max_length=6)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rank'],
            },
        ),
    ]
