# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
