# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='profile_photo',
            field=models.ImageField(default='default_avatar/avatar.png', upload_to='users'),
        ),
    ]
