# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2017, 9, 6), editable=False),
        ),
    ]
