# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190529_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='redeemed_points',
        ),
    ]
