# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170906_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
