# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170907_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={'ordering': ['points']},
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='rank',
        ),
    ]
