# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170908_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
