# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170920_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
