# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170920_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
