# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 17:50
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170920_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='profile_photo',
            field=models.ImageField(default='default_avatar/avatar.png', upload_to=accounts.models.content_file_name),
        ),
    ]
