# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170923_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='share_code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
