# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171221_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='share_code',
            field=models.CharField(blank=True, default=b'A8D1B1', max_length=8, unique=True),
        ),
    ]
