# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20171221_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='share_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
