# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 09:48
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='profile_photo',
            field=models.ImageField(default='static/accounts/img/user.png', upload_to=accounts.models.content_file_name),
        ),
    ]
