# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 10:24
from __future__ import unicode_literals

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180129_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='profile_photo',
            field=models.ImageField(default='default_avatar/avatar.png', upload_to=accounts.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='share_code',
            field=models.CharField(blank=True, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code=None, message='Share code must not exceed 6 characters', regex='^.{6}$')]),
        ),
    ]
