# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180206_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
