# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tuser_acceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='acceptance',
        ),
    ]
