# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-23 06:33
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190323_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
