# Generated by Django 2.2.4 on 2019-08-25 17:19

import accounts_api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=15, unique=True)),
                ('phone_number', models.CharField(error_messages={'unique': 'A user with this phone number already exists.'}, max_length=13, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('address', models.CharField(max_length=30)),
                ('referrer_prize', models.IntegerField(default=0, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(default='default_avatar/avatar.png', upload_to=accounts_api.models.content_file_name)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, default='', max_length=6)),
                ('is_agreed', models.BooleanField(default=False)),
                ('share_code', models.CharField(blank=True, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code=None, message='Share code must not exceed 6 characters', regex='^.{6}$')])),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['referrals'],
            },
        ),
    ]
