# Generated by Django 3.0.6 on 2020-05-15 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0004_auto_20190831_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='reset_password',
            name='password_reset',
        ),
        migrations.AddField(
            model_name='reset_password',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 10, 9, 31, 847356, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reset_password',
            name='reset_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
