# Generated by Django 3.0.6 on 2020-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0005_auto_20200515_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with this phone number already exists.'}, max_length=15, unique=True),
        ),
    ]
