# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsum',
            name='dates',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
