# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylotto',
            name='end_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dailylotto',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 22, 12, 6, 12, 907952, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
