# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0002_auto_20170902_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylotto',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2017, 9, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='dailylotto',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2017, 9, 7), editable=False),
        ),
    ]
