# Generated by Django 2.2.4 on 2019-08-24 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0003_auto_20190622_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylotto',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 12, 5, 58, 798348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylotto',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
