# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0003_auto_20170907_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylotto',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
