# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0005_auto_20170907_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylotto',
            name='end_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
