# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_lotto', '0007_auto_20170907_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylottoticket',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
