# Generated by Django 2.2.4 on 2019-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Messages',
                'db_table': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=230)),
                ('slug', models.SlugField(max_length=230, unique=True)),
                ('answer', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Faq',
                'ordering': ['question'],
            },
        ),
    ]
