# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_url',
        ),
    ]
