# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0002_remove_game_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=1, max_length=230, unique=True),
            preserve_default=False,
        ),
    ]
