# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0002_delete_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_stat',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Game statistic', 'verbose_name_plural': 'Game statistics'},
        ),
    ]
