# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0003_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_stat',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
    ]
