# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0004_game_stat_times_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_stat',
            name='times_played',
        ),
    ]
