# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0005_remove_game_stat_times_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='played_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_played', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tossapp.Game')),
            ],
        ),
    ]
