# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0006_played_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='played_stat',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='played_stat',
        ),
    ]
