# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0007_auto_20170830_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='times_played',
            field=models.BigIntegerField(default=0),
        ),
    ]
