# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0008_auto_20170830_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
