# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0010_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question'], 'verbose_name_plural': 'Faq'},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='detail',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
    ]
