# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0011_auto_20170913_1631'),
        ('tossapp', '0011_auto_20170911_2317'),
    ]

    operations = [
    ]
