# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0012_merge_20170920_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_status',
            field=models.BooleanField(default=False),
        ),
    ]
