# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0013_notification_seen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='your_subject',
        ),
    ]
