# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import tossapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tossapp', '0014_remove_contact_us_your_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='display_photo',
            field=models.ImageField(default=None, upload_to=tossapp.models.content_file_name),
        ),
    ]
